name: Steps

on:
  schedule:
  - cron: 50 0 * * *

jobs:
  sys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - run: npm install
      - run: npm start
