name: Steps

on:
  schedule:
  - cron: 50 0 * * *

jobs:
  sys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - name: Run task
        run: |
          # install dependencies
          npm install
          # start task
          npm start
