# 每日任务
name: "Task"

on: 
  schedule: 
  # 每日定时7点50分跑一次任务
  - cron: "50 0 * * *"
jobs: 
  task: 
    # 设置运行环境
    runs-on: "ubuntu-latest"
    steps: 
    # 检出项目代码
    - uses: "actions/checkout@v2"
    # 安装依赖 & 运行
    - name: "Use Node.js"
      uses: "actions/setup-node@v1"
      with: 
        node-version: "12"
    - run: "npm install"
    - run: "npm run task"