name: Task

on:
  schedule:
  - cron: 50 0 * * *

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Run Task
      run: |
        # install dependencies
        npm install
        # start
        npm run task
