name: test steps

on:
  pull_request:
    branches:
    - main

jobs:
  sys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run steps
        run: bash task/steps.sh
